.DEFAULT_GOAL := test

.PHONY: help clean piptools requirements dev_requirements \
        validation_requirements doc_requirementsprod_requirements static shell \
        test coverage isort_check isort style lint quality validate \
        migrate html_coverage upgrade compile_translations dummy_translations \

define BROWSER_PYSCRIPT
import os, webbrowser, sys
try:
	from urllib import pathname2url
except:
	from urllib.request import pathname2url

webbrowser.open("file://" + pathname2url(os.path.abspath(sys.argv[1])))
endef
export BROWSER_PYSCRIPT
BROWSER := python -c "$$BROWSER_PYSCRIPT"

# Generates a help message. Borrowed from https://github.com/pydanny/cookiecutter-djangopackage.
help: ## display this help message
	@echo "Please use \`make <target>\` where <target> is one of"
	@awk -F ':.*?## ' '/^[a-zA-Z]/ && NF==2 {printf "\033[36m  %-25s\033[0m %s\n", $$1, $$2}' $(MAKEFILE_LIST) | sort

clean: ## delete generated byte code and coverage reports
	find . -name '*.pyc' -delete
	coverage erase
	rm -rf assets
	rm -rf pii_report

piptools: ## install pinned version of pip-compile and pip-sync
	pip install -r requirements/pip-tools.txt

requirements: piptools dev_requirements ## sync to default requirements

dev_requirements: ## sync to requirements for local development
	pip-sync -q requirements/base.txt

prod_requirements: ## install requirements for production
	npm install
	pip-sync -q requirements/production.txt

static: ## generate static files
	npm run-script build
	python manage.py collectstatic --noinput

dev_static: ## generate static files
	npm start
	python manage.py collectstatic --noinput

shell: ## run Django shell
	python manage.py shell

test: clean ## run tests and generate coverage report
	coverage run --source ./apps manage.py test --settings=xman.settings.test
	coverage report -m --fail-under=90

isort_check: ## check that isort has been run
	isort --check-only apps/

isort: ## run isort to sort imports in all Python files
	isort --recursive --atomic apps/

style: ## run Python style checker
	pycodestyle ./apps

lint: ## run Python code linting
	pylint ./apps --rcfile=./setup.cfg

quality: style isort_check lint ## check code style and import sorting, then lint
	diff-quality --violations=pylint --fail-under=100 --options="--rcfile=./setup.cfg"

validate: test quality ## run tests, quality.

migrate: ## apply database migrations
	python manage.py migrate

upgrade: export CUSTOM_COMPILE_COMMAND=make upgrade
upgrade: piptools ## update the requirements/*.txt files with the latest packages satisfying requirements/*.in
	# Make sure to compile files after any other files they include!
	pip-compile --upgrade -o requirements/pip-tools.txt requirements/pip-tools.in
	pip-compile --upgrade -o requirements/base.txt requirements/base.in
	pip-compile --upgrade -o requirements/test.txt requirements/test.in

run: requirements migrate
	python manage.py runserver

